name: celene_cli
description: App to access celene (Moodle E-Learning platform) from the terminal. Comes with file management, session persistance and other features
version: 1.0.2
repository: https://github.com/tkdev1755/celene_cli

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  archive: ^4.0.5
  args: ^2.4.2
  beautiful_soup_dart: ^0.3.0
  consola: ^0.1.0
  console: ^4.1.0
  dart_console: ^4.1.1
  encrypt: ^5.0.3
  ffi: ^2.1.4
  http: ^1.3.0
  http_session: ^0.2.2
  intl: ^0.19.0
  path: ^1.9.1
  secure_session: ^1.0.5
  uuid: ^4.5.1

dev_dependencies:
  ffigen: ^18.1.0
  lints: ^4.0.0
  test: ^1.24.0
